name: Build and Deploy Docker image to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurar Docker Buildx (opcional pero recomendado para mejorar la construcción)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Configurar Docker Hub login
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Construir la imagen de Docker
    - name: Build Docker image
      run: |
        docker build -t my-nginx-app .

    # 5. Subir la imagen a Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push my-nginx-app

    # 6. Desplegar la imagen a la instancia EC2
    - name: Deploy to EC2
      run: |
        ssh -i "${{ secrets.EC2_SSH_KEY }}" -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << EOF
          docker pull my-nginx-app
          docker run -d -p 80:80 my-nginx-app
        EOF
